version: "3"

volumes:
  mongo_data:

services:
  mongodb:
    image: mongo:4.4
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}

  bot:
    image: warzonestats-bot:latest
    build: .
    restart: always
    depends_on:
      - mongodb
    environment:
      TOKEN: ${DISCORD_TOKEN}
      MONGO_URI: mongodb://${MONGODB_USER}:${MONGODB_PASS}@mongodb
      MONGO_DBNAME: ${MONGO_DBNAME}

  ### Database inspection ###

  mongo-express:
    image: mongo-express
    profiles: [ "inspect" ]
    depends_on:
      - mongodb
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASS}
